### ISSUE TITLE
Investigate why web3 browser is not detected

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/www.trustlines.foundation#16]
Investigate why on the merkle drop page status and coinbase wallet are not detected as a web3 browser.

**Comment by weilbith** [comment]
Fist input:
- when I run the font- and backend in a local network, with _Status_ the web-app reports that it can't determine the chain and intend to sign the transaction does nothing. _Coinbase_ works and reports that I'm connected to the wrong chain. But I can't switch to Goerli (settings > advanced > active network > ETH) and no custom network can be added.
- The link to the Coinbase developer documentation does not work (still points to the toshi domain), the discord support hasn't reacted yet.
- Status has some documentation and it appears like they actually support `window.ethereum`, what the local test kinda verifies. The displayed error comes from a try and catch. I hope that sentry can give me an inview for that.

**Comment by berndbohmeier** [comment]
what error do you see? Do you see the console output on status?

**Comment by weilbith** [comment]
The error is: `Error: Node error: {"code":-32601,"message":"The method eth_chainId does not exist/is not available"}`

**Comment by weilbith** [comment]
But this does not explain while the demo page doesn't find `window.ethereum` at all.

**Comment by weilbith** [comment]
The Merkle Drop on Kovan does work (if not 100% yet) with my local setup and Coinbase.

**Comment by weilbith** [comment]
The output by status for `web3.currentProvider` is `{"host":"CustomProvider","connection":{}}`

**Comment by weilbith** [comment]
Okay, Coinbase worked for me with my local back- and frontend, plus the deployment on Kovan. I was able to successfully withdraw my tokens.

**Comment by berndbohmeier** [comment]
> The error is: Error: Node error: {"code":-32601,"message":"The method eth_chainId does not exist/is not available"} 

Maybe we dont catch that error properly. We have two handlers, one should set it to unknown chain, and the other will set it to not connected. 
I wonder which method they want us to use.

**Comment by weilbith** [comment]
I got the error from [here](https://github.com/trustlines-protocol/www.trustlines.foundation/blob/59e66a128aa74e057f0e9c60e6dae0f00baadfdd/src/js/merkle-drop/state/chainState.js#L33). So the handler that set it then to unknown chain. That goes for the local setup.

**Comment by weilbith** [comment]
I put the Status app into debug mode and investigated it from the PC. Accessing the demo page offers no `window.ethereum` object. I don't know why. With the local setup it exists. When I enable in the app to trust all Dapps, I can access it, getting the account etc. But the chain ID is not accessible.
When the app does not trust Dapps it requires to call the asynchronous `window.ethereum.enable()` function.

**Comment by weilbith** [comment]
I checked this problem again with the productive version which is live now. And it works. I get the messages that my account does not match with the inserted address which is eligible. Thereby the modern web-browser must be registered.
So it seems like the guess is correct that the demo/test page did not pass some security standard which such wallets check. I can't name the exact property.

This issue can be closed since it works in production.
