### ISSUE TITLE
Make error recognizable as such

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/www.trustlines.foundation#18]
Currently the errors are just in a blue box and can not be recognized as errors or warnings. 
Sit together with Sash and work out a new design to show the error as errors.

**Comment by weilbith** [comment]
I had a call with Sash to show her the current situation and the problem. She wanted to have some screenshots for the scenarios. She will provide us with the designs here in this issue.

**Comment by sashseurat** [comment]
Here are the drafts for the redesigns:

![claiming-failed](https://user-images.githubusercontent.com/32264127/72620453-9f815e80-393f-11ea-9fc2-7392d24ea7b9.png)
![error](https://user-images.githubusercontent.com/32264127/72620454-9f815e80-393f-11ea-8bd9-b8342d3ddc66.png)
![no-error](https://user-images.githubusercontent.com/32264127/72620455-a019f500-393f-11ea-9e11-ea6628b193bb.png)
![with-error](https://user-images.githubusercontent.com/32264127/72620456-a019f500-393f-11ea-861a-9a3b1e5eeaa1.png)
![yes-with-error](https://user-images.githubusercontent.com/32264127/72620457-a019f500-393f-11ea-9f7a-f678605dd886.png)

And here is a link to the designs in Invision for inspection:
https://invis.io/H2VLID2PDBX

**Comment by berndbohmeier** [comment]
That's pretty much what we had before and looks in my opinion like my computer is about to explode. 
I would love to have something that makes clear there is a problem, but looks a bit nicer.

**Comment by sashseurat** [comment]
If the issue is not error's colors, but rather the layout itself, or whatever else, maybe it makes sense to get a bit of a more descriptive brief.
Once thats there, I can sit with Thore and find a better solution and post new drafts.

**Comment by berndbohmeier** [comment]
I think it is the combination of red and this triangle symbol. 
If it is only me that thinks that's looks like a nuclear warning we can also leave it.
@andfletcher

**Comment by berndbohmeier** [comment]
Maybe more like https://images.app.goo.gl/3rqkR8CZpjAdnL5c8

**Comment by sashseurat** [comment]
How about these:

![claiming-failed](https://user-images.githubusercontent.com/32264127/72623083-c4c49b80-3944-11ea-9ba3-2c77d5b031a1.png)

![error](https://user-images.githubusercontent.com/32264127/72623193-f3427680-3944-11ea-9b41-95504ca7fc0b.png)

**Comment by andfletcher** [comment]
Let's go with that version. Looks good.

**Comment by berndbohmeier** [comment]
Yeah, much better. Maybe also add that to the "wrong chain" and so on messages?

**Comment by sashseurat** [comment]
Sure, here you go (all together now):

![claiming-failed](https://user-images.githubusercontent.com/32264127/72624197-cbeca900-3946-11ea-84ba-1871850a2b25.png)

![error](https://user-images.githubusercontent.com/32264127/72624199-cbeca900-3946-11ea-8bf1-033dbde3ab54.png)

![no-error](https://user-images.githubusercontent.com/32264127/72624200-cbeca900-3946-11ea-949c-7875b3b10331.png)

![with-error](https://user-images.githubusercontent.com/32264127/72624201-cbeca900-3946-11ea-9756-8f8c7fc040dc.png)

![yes-with-error](https://user-images.githubusercontent.com/32264127/72624203-cc853f80-3946-11ea-942e-50309faeae9c.png)

**Comment by berndbohmeier** [comment]
Yes, Looks good to me.
