### ISSUE TITLE
Exclude debug whoami span in production build

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/www.trustlines.foundation#46]
to not accidentally put it on the website.

**Comment by schmir-at-bb** [comment]
As I already explained we should rather display the production build with the changed merkle drop parameters on the preview page including the whoami information. This would need some more work.

i.e. please don't fix this by excluding the span. If you fear that this is really an issue, fix the `yarn deploy` command instead or the instructions how to deploy the website.

The way forward for me would be:
1. show a production build as preview
2. have a preview for the master branch
3. deploy from circleci

**Comment by schmir-at-bb** [comment]
Beside from what I can tell, there are more serious user errors that can go wrong:

- Accidentally run `yarn deploy` from wrong branch
- Run `yarn deploy` from non up-to-date master branch
- Run `yarn deploy` with outdated dependencies

**Comment by berndbohmeier** [comment]
For me the production build is the one that is used only in production, so it should not include dev information, but if you plan on having the production build also as the preview and changing the way we deploy that solves the same problem for me. It should be hard to make a mistake when deploying. 

> Accidentally run yarn deploy from wrong branch
> Run yarn deploy from non up-to-date master branch
> Run yarn deploy with outdated dependencies

Yes, they are more serious but also more obvious to me than a `WHOAMI` variable deep in the code.
I know that I should run `yarn deploy` from an up to date master branch, but I would have no idea that the WHOAMI variable exists if I would have not read the PR.

**Comment by berndbohmeier** [comment]
Closed, because we will deploy from circle CI

**Comment by schmir-at-bb** [comment]
For the moment, I've opened #47, which also contains a commit that makes sure WHOAMI is empty when running yarn deploy.

**Comment by berndbohmeier** [comment]
Thanks
