### ISSUE TITLE
Auction flow design changes

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/www.trustlines.foundation#75]
I the session with Bernd, Sash and Tatu we came up with the following design changes:
I separated them in nice to have and must have, lets try to finish the must to have first.
If you pick one, please put your name in the brackets.

### Must have
- [x] Change hover effect of button to not change the font color to black, use some lighter color for the background instead (bernd)
- [ ] Change step title margin bottom to `margin-bottom: 15px` (to minimize space between title and text thereafter)
- [x] Show T and S later in the flow or show error screens like not whitelisted earlier (bernd) 
      Andreas said it is better to do it in the beginning 
- [x] Change text in header to "Approve Transfer" (bernd)
- [x] Link to TLN contract and Auction contract in effected screens()
- [x] Make current slot price bold ()

- [x] Make button font weight `font-weight: 600` (Côme)

- [x] Make button (.button.is-rounded) `height: 50px` (Côme)

- [ ] Change line height for running text (.content) to: `line-height: 1.4` ()

- [ ] Change line height for title (.title) to: `line-height: 0.125` ()

- [ ] Remove this line: `width: 100%;` from this declaration: `.modal-content, .modal-card` (it solved for me the problem of T&C dialog being too wide) ()

- [ ] Add this line: `padding: 50px 0 50px 0;` to this element: `@media screen and (min-width: 769px), print
.column.is-8.is-offset-2`
(it evens the space on top & bottom in white box) ()

### Nice to have
- [x] Show how much was bid in already bid screen ()
- [ ] Show more information on the not enough TLN screen, like current price, end price, how much TLN the person have and maybe when he can bid? ()
- [ ] Show a warning in the confirmation screen if transaction is taking too long

**Comment by sashseurat** [comment]
changed in description the spaceing between title and text, and font weight to 600 (700 was incorrect)

**Comment by sashseurat** [comment]
Draft for placement of box after stats, with icon for more info, and example of use of big numbers in shorthand is ready for review @berndbohmeier & @Smokyish :
![Auction Draft](https://user-images.githubusercontent.com/32264127/83030848-25bb5900-a034-11ea-8315-72a82e705eb3.png)

**Comment by andfletcher** [comment]
Auction is up and running. Further design changes would be nice to have but not needed and since the auction is running we should not make any changes during the time it is running. Therefore closing this. If anyone thinks we NEED to make any design changes please let me know.
